### ISSUE TITLE
说明文档有点不全

### ISSUE THREAD

**Issue by sm0king** [wdfe/ideploy#1]
关于nginx的配置，有点不全. . .
使用目录下的 nginx.conf ，将 node_port 改成src/common/config/config.js 里的端口（port） 但不能与nginx里的端口一样。

**Comment by luyongfugx** [comment]
嗯，nginx.conf 其实是thinkjs自带的，这个我们清理一下，并再过下文档有没有问题的地方

**Comment by sm0king** [comment]
还有个小问题，貌似对git的版本也有依赖，貌似要2.0以后的版本，我用的 centos 6.5 自带的git版本只有1.7在拉代码的时候报错了。刚才升级了git版本到最新，可以了。

**Comment by luyongfugx** [comment]
@sm0king 多谢反馈，因为我们一开始版本就高一些，所以没碰到这个问题，现在能跑起来吗

**Comment by sm0king** [comment]
@luyongfugx  可以了，跑起来了~

**Comment by luyongfugx** [comment]
@sm0king  good 有问题及时反馈！

**Comment by williambryan777** [comment]
你这个支持SVN吗

**Comment by sm0king** [comment]
在新建机器的时候，很多地方 比如项目构建任务等多个地方并不是必填的，前端却显示是必填的
然而却可以用空格忽悠一下验证
这 . . .

**Comment by sm0king** [comment]
@williambryan777  可以，支持SVN。
src/common/config/config.js 
配置信息里写 cvsUser和cvsPass 就好了
git的话应该是删除这两个选项。
PS:你可以试一下，我现在用的git，是把这两个配置信息删掉了的。
